name: TasMan Publish

on:
  push:
    branches: [ main ]

env:
  #REPOSITORY_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  CURRENT_REPO_URL: https://github.com/${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Package
        run: dotnet pack -c Release -o out -p:PackageVersion=${{ steps.semantic.outputs.new_release_version }} -p:RepositoryUrl=${{env.CURRENT_REPO_URL}}

    #   - name: Publish the package to nuget.org
    #     run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true -k ${{ secrets.NUGET_AUTH_TOKEN}} -s https://api.nuget.org/v3/index.json

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo released full version: ${{ steps.semantic.outputs.new_release_version }}
          echo released major version: ${{ steps.semantic.outputs.new_release_major_version }}
          echo released minor version${{ steps.semantic.outputs.new_release_minor_version }}
          echo released patch version${{ steps.semantic.outputs.new_release_patch_version }}